require: rubocop-rspec

AllCops:
  Exclude:
    - "db/**/*"
    - "bin/*"
    - "lib/tasks/**/*"
    - "lib/capistrano/**/*"
    - "Gemfile"
    - "config/**/*"
    - "vendor/**/*"
    - "app/views/**/*"
    - "config.ru"
    - "Rakefile"
    - "app/channels/application_cable/**"
    - "spec/spec_helper.rb"

RSpec/MultipleExpectations:
  Exclude:
    - "spec/requests/**/*"

RSpec/NamedSubject:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Lambda:
  Exclude:
    - "app/forms/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Security/Eval:
  Enabled: true
  Exclude:
    - "spec/**/*"

MethodLength:
  Max: 15
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20
  Exclude:
    - "app/services/post_creater_service.rb"

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/IfUnlessModifier:
  Enabled: false

Style/AlignArray:
  Enabled: false

Style/WordArray:
  Enabled: false
