default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

server: &server
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432

development:
  <<: *default
  <<: *server
  database: yemenportal_development

test:
  <<: *default
  <<: *server
  database: yemenportal_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
