a: href
applet:
  - codebase
  - archive
area: href
audio: src
base: href
blockquote: cite
body: background
button: formaction
command: icon
del: cite
embed: src
form: action
frame:
  - longdesc
  - src
head: profile
html: manifest
iframe:
  - longdesc
  - src
img:
  - longdesc
  - src
  - usemap
  - srcset
input:
  - src
  - usemap
  - formaction
ins: cite
link: href
object:
  - classid
  - codebase
  - archive
  - data
  - usemap
q: cite
script: src
source:
  - src
  - srcset
video:
  - poster
  - srcw
