default: &default
  post_count: 1000
  min_weight: 4.0
  hours_period: 3
  min_percent: 0.8

development:
  *default
test:
  post_count: 1000
  min_weight: 2.0
  hours_period: 3
  min_percent: 0.8
production:
  *default
